language: perl
perl:
    - "5.32"
    - "5.30"
    - "5.28"
    - "5.26"
    - "5.24"
    - "5.22"
    - "5.20"
    - "5.18"

env:
    - TEST_SPIDER=1

install:
    - dzil authordeps --missing | cpanm --no-skip-satisfied || { cat ~/.cpanm/build.log ; false ; }
    - dzil listdeps --author --missing | cpanm --no-skip-satisfied || { cat ~/.cpanm/build.log ; false ; }

script:
    - RELEASE_TESTING=1 dzil test --author --release

dist: xenial
os: linux
cache:
  directories:
    - $HOME/perl5/perlbrew/perls
