language: perl
perl:
  - "dev"
  - "5.30"
  - "5.28"
  - "5.26"

env:
    - TEST_SPIDER=1

install:
    - dzil authordeps --missing | cpanm --no-skip-satisfied || { cat ~/.cpanm/build.log ; false ; }
    - dzil listdeps --author --missing | cpanm --no-skip-satisfied || { cat ~/.cpanm/build.log ; false ; }

script:
    - RELEASE_TESTING=1 dzil test --author --release

before_install:
  - eval $(curl https://travis-perl.github.io/init) --auto

dist: xenial
os: linux
cache:
  directories:
    - $HOME/perl5
