on:
  pull_request:
  push:
    branches:
      - master

name: Build and Test
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-latest', 'macos-latest']
        perl: [ '5.36', '5.34', '5.32' ]
    name: Perl ${{ matrix.perl }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl }}
      - run: perl -V
      - name: Install dependencies
        run: |
          cpan Dist::Zilla Dist::Zilla::Role::ModuleMetadata App::cpanminus
          dzil authordeps --missing | cpanm
      - name: build
        run: dzil build
      - name: test
        run: RELEASE_TESTING=1 TEST_SPIDER=1 dzil test --author --release
