on:
  pull_request:
  push:
    branches:
      - master

name: Build and Test
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-latest', 'macos-latest']
        perl: [ '5.36', '5.34', '5.32' ]
    name: Perl ${{ matrix.perl }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl }}
      - run: perl -V
      - name: OS dependencies
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
            sudo apt-get update && sudo apt-get install -y locales && locale -a && sudo locale-gen en_US.UTF-8
          elif [ "$RUNNER_OS" == "macOS" ]; then
            brew install automake
            cpan XML::LibXML
          fi
      - name: Install build dependencies
        run: |
          cpan CPAN::DistnameInfo Dist::Zilla Dist::Zilla::Role::ModuleMetadata
          dzil authordeps --missing | cpanm
      - name: Install module dependencies
        run: dzil listdeps --missing | cpanm
      - name: build
        run: dzil build
      - name: test
        run: RELEASE_TESTING=1 TEST_SPIDER=1 dzil test --author --release
